[package]
name = "xyz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
serde = "1.0.202"
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2" , features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
worker = { version = "0.3.0", features = ["axum", "http"] }
worker-macros = "0.3.0"
