app = 'alexkanxyz'
primary_region = 'ewr'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
