// Board formatting mirrors the Vesta CLI; fixtures generated by the CLI guard parity.
export interface BoardQuote { label: string; price: number; changePercent: number }

// Python rounds the exact binary float to even on ties. Multiplying by 10
// first in JS changes some ties; decode the float to preserve CLI behavior.
export function roundDecimal(value: number, digits: number): number {
    if (!Number.isFinite(value)) throw new Error("invalid_number");
    const view = new DataView(new ArrayBuffer(8));
    view.setFloat64(0, Math.abs(value));
    const bits = view.getBigUint64(0);
    const exponent = Number((bits >> 52n) & 2047n);
    const fraction = bits & ((1n << 52n) - 1n);
    const mantissa = exponent === 0 ? fraction : fraction + (1n << 52n);
    const shift = exponent === 0 ? -1074 : exponent - 1023 - 52;
    let numerator = mantissa * 10n ** BigInt(digits);
    let denominator = 1n;
    if (shift >= 0) numerator <<= BigInt(shift);
    else denominator <<= BigInt(-shift);
    let rounded = numerator / denominator;
    const remainder = numerator % denominator;
    if (remainder * 2n > denominator || (remainder * 2n === denominator && rounded % 2n !== 0n)) rounded++;
    const result = Number(rounded) / 10 ** digits;
    return result === 0 ? 0 : Math.sign(value) * result;
}

const CHAR_CODES = Object.fromEntries([
    ...Array.from("ABCDEFGHIJKLMNOPQRSTUVWXYZ", (char, i) => [char, i + 1]),
    ...Array.from("1234567890", (char, i) => [char, i + 27]),
    [" ", 0], ["$", 40], ["-", 44], ["+", 46], ["%", 54], [",", 55], [".", 56],
]) as Record<string, number>;

export function formatBoard(quotes: BoardQuote[]): number[][] {
    if (quotes.length !== 6) throw new Error("incomplete_snapshot");
    return quotes.map(({ label, price, changePercent }) => {
        if (!/^[A-Z0-9]{1,6}$/.test(label) || !Number.isFinite(price) || price <= 0 || !Number.isFinite(changePercent)) throw new Error("invalid_quote");
        const rounded = roundDecimal(changePercent, 1);
        const change = `${rounded >= 0 ? "+" : ""}${rounded.toFixed(1)}%`;
        let amount = roundDecimal(price, price >= 100 ? 0 : 2).toFixed(price >= 100 ? 0 : 2);
        if (price >= 1000) amount = amount.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
        const priceText = `$${amount}`;
        if (priceText.length > 8 || change.length > 6) throw new Error("board_overflow");
        const text = `${label.padEnd(6)} ${priceText.padStart(8)}${change.padStart(6)} `;
        const row = Array.from(text, (char) => CHAR_CODES[char]);
        row[21] = rounded > 0 ? 66 : rounded < 0 ? 63 : 70;
        if (row.length !== 22 || row.some((code) => code === undefined)) throw new Error("board_overflow");
        return row;
    });
}

