//! Link-preview (Open Graph / Twitter) tags for every HTML page, added at the edge so
//! iMessage, Slack, Discord, etc. show the site card without each page repeating them.
//!
//! A page overrides any default by declaring that tag itself, e.g.
//! `<meta property="og:image" content="/assets/other.jpg">`. Root-relative `content`
//! paths are made absolute, since crawlers don't resolve them.

const SITE_NAME: &str = "alexkan.xyz";
const DEFAULT_DESCRIPTION: &str = "Alex Kan's personal website.";
// 1200x630 card generated by scripts/og.py
const DEFAULT_IMAGE: &str = "/assets/og.jpg";
const DEFAULT_IMAGE_ALT: &str = "alexkan.xyz, Alex Kan's personal website";

/// Adds every preview tag `html` doesn't already declare, just before `</head>`.
pub fn add_tags(html: &str, origin: &str, path: &str) -> String {
    let html = html.replace("content=\"/", &format!("content=\"{origin}/"));
    let Some(head_end) = html.find("</head>") else {
        return html;
    };

    let title = meta(&html, "og:title")
        .or_else(|| page_title(&html))
        .unwrap_or_else(|| SITE_NAME.to_string());
    let description = meta(&html, "og:description")
        .or_else(|| meta(&html, "description"))
        .unwrap_or_else(|| DEFAULT_DESCRIPTION.to_string());
    let page_image = meta(&html, "og:image");
    let image = page_image
        .clone()
        .unwrap_or_else(|| format!("{origin}{DEFAULT_IMAGE}"));

    let mut tags = vec![
        ("name", "description", description.clone()),
        ("name", "theme-color", "#f4f4f4".to_string()),
        ("property", "og:type", "website".to_string()),
        ("property", "og:site_name", SITE_NAME.to_string()),
        ("property", "og:locale", "en_US".to_string()),
        ("property", "og:title", title.clone()),
        ("property", "og:description", description.clone()),
        ("property", "og:url", format!("{origin}{path}")),
        ("property", "og:image", image.clone()),
    ];
    // Only describe the default card; a page's own image has its own dimensions
    if page_image.is_none() {
        tags.extend([
            ("property", "og:image:type", "image/jpeg".to_string()),
            ("property", "og:image:width", "1200".to_string()),
            ("property", "og:image:height", "630".to_string()),
            ("property", "og:image:alt", DEFAULT_IMAGE_ALT.to_string()),
        ]);
    }
    // X reads twitter:*; set explicitly rather than relying on its og:* fallback
    tags.extend([
        ("name", "twitter:card", "summary_large_image".to_string()),
        ("name", "twitter:title", title),
        ("name", "twitter:description", description),
        ("name", "twitter:image", image),
    ]);

    let mut added = String::new();
    for (attr, key, value) in tags {
        if meta(&html, key).is_none() {
            added += &format!("<meta {attr}=\"{key}\" content=\"{value}\">\n");
        }
    }
    // Small site icon in iMessage and Slack previews
    if !html.contains("rel=\"apple-touch-icon\"") {
        added += "<link rel=\"apple-touch-icon\" href=\"/assets/apple-touch-icon.png\">\n";
    }

    let mut out = html.clone();
    out.insert_str(head_end, &added);
    out
}

/// `content` of the `<meta>` tag whose `property` or `name` is `key`.
fn meta(html: &str, key: &str) -> Option<String> {
    let at = [format!("property=\"{key}\""), format!("name=\"{key}\"")]
        .iter()
        .find_map(|attr| html.find(attr.as_str()))?;
    let start = html[..at].rfind('<')?;
    let tag = &html[start..at + html[at..].find('>')?];
    let content = &tag[tag.find("content=\"")? + "content=\"".len()..];
    Some(content[..content.find('"')?].to_string())
}

/// Text of `<title>`, escaped for use inside an attribute.
fn page_title(html: &str) -> Option<String> {
    let start = html.find("<title>")? + "<title>".len();
    let end = start + html[start..].find("</title>")?;
    Some(html[start..end].trim().replace('"', "&quot;"))
}

#[cfg(test)]
mod tests {
    use super::*;

    const ORIGIN: &str = "https://alexkan.xyz";

    fn page(head: &str) -> String {
        format!(
            "<html><head><title>Projects | alexkan.xyz</title>{head}</head><body></body></html>"
        )
    }

    #[test]
    fn bare_page_gets_default_card() {
        let html = add_tags(&page(""), ORIGIN, "/projects");
        assert_eq!(meta(&html, "og:title").unwrap(), "Projects | alexkan.xyz");
        assert_eq!(meta(&html, "og:description").unwrap(), DEFAULT_DESCRIPTION);
        assert_eq!(
            meta(&html, "og:url").unwrap(),
            "https://alexkan.xyz/projects"
        );
        assert_eq!(
            meta(&html, "og:image").unwrap(),
            "https://alexkan.xyz/assets/og.jpg"
        );
        assert_eq!(meta(&html, "og:image:width").unwrap(), "1200");
        assert_eq!(
            meta(&html, "twitter:image").unwrap(),
            "https://alexkan.xyz/assets/og.jpg"
        );
        assert!(html.contains("apple-touch-icon"));
        assert!(html.find("og:image").unwrap() < html.find("</head>").unwrap());
    }

    #[test]
    fn page_description_feeds_og_and_twitter() {
        let head = r#"<meta name="description" content="Things I've built.">"#;
        let html = add_tags(&page(head), ORIGIN, "/projects");
        assert_eq!(meta(&html, "og:description").unwrap(), "Things I've built.");
        assert_eq!(
            meta(&html, "twitter:description").unwrap(),
            "Things I've built."
        );
        assert_eq!(html.matches("name=\"description\"").count(), 1);
    }

    #[test]
    fn page_image_overrides_default() {
        let head = r#"<meta property="og:image" content="/assets/other.jpg">"#;
        let html = add_tags(&page(head), ORIGIN, "/projects");
        assert_eq!(
            meta(&html, "og:image").unwrap(),
            "https://alexkan.xyz/assets/other.jpg"
        );
        assert_eq!(
            meta(&html, "twitter:image").unwrap(),
            "https://alexkan.xyz/assets/other.jpg"
        );
        assert_eq!(html.matches("property=\"og:image\"").count(), 1);
        assert!(meta(&html, "og:image:width").is_none());
    }

    #[test]
    fn preview_host_gets_its_own_urls() {
        let html = add_tags(&page(""), "https://pr-9-xyz.akan72.workers.dev", "/");
        assert_eq!(
            meta(&html, "og:image").unwrap(),
            "https://pr-9-xyz.akan72.workers.dev/assets/og.jpg"
        );
    }

    #[test]
    fn links_are_left_alone() {
        let head = r#"<link rel="icon" href="/assets/favicon.ico">"#;
        let html = add_tags(&page(head), ORIGIN, "/");
        assert!(html.contains(r#"href="/assets/favicon.ico""#));
    }

    #[test]
    fn quotes_in_title_are_escaped() {
        let html = add_tags("<head><title>Say \"hi\"</title></head>", ORIGIN, "/");
        assert!(html.contains(r#"content="Say &quot;hi&quot;""#));
    }

    #[test]
    fn html_without_head_is_unchanged() {
        assert_eq!(add_tags("<p>hi</p>", ORIGIN, "/"), "<p>hi</p>");
    }
}
